[package]
name = "icicle-hash"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Rust wrapper for the CUDA implementation of hash functions by Ingonyama"
homepage.workspace = true
repository.workspace = true

[dependencies]
icicle-core = { workspace = true }
icicle-cuda-runtime = { workspace = true }

[dev-dependencies]
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
itertools = "0.12.0"

[build-dependencies]
cmake = "0.1.50"

[features]
default = []
