name: Extract Icicle Backend Branch

on:
  workflow_call:
    inputs:
      pr-number:
        description: 'The PR number to fetch the description for'
        required: true
        type: number
    outputs:
      metal-backend-branch:
        description: "Branch name for metal backend"
        value: ${{ jobs.extract-metal-backend-branch.outputs.metal-backend-branch }}

jobs:
  extract-metal-backend-branch:
    name: Extract metal branch name
    runs-on: ubuntu-22.04
    outputs:
      metal-backend-branch: ${{ steps.extract.outputs.metal-backend-branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Private Branch from PR Description
        id: extract
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DESCRIPTION=$(gh pr view ${{ inputs.pr-number }} --json body -q '.body')
          echo "PR Description: $DESCRIPTION"
          METAL_BE_BRANCH=$(echo "$DESCRIPTION" | grep -oP 'metal-backend-branch:\s*\K[^\s]+') || true
          if [ -z "$METAL_BE_BRANCH" ]; then
            METAL_BE_BRANCH="main" # Default branch if not specified
          fi
          echo "Extracted METAL Backend Branch: $METAL_BE_BRANCH"
          echo "metal-backend-branch=$METAL_BE_BRANCH" >> "$GITHUB_OUTPUT"